### PR TITLE
Add RUSTDOCFLAGS to cargo test

### PR DESCRIPTION
**Pull request by sylwiaszunejko**
Changes provided by this PR:
* RUSTDOCFLAGS added to cargo test
* It is needed to correctly compile tests (examples) from the documentation

### CODE REVIEW

**Comment by piodul** [comment]
@sylwiaszunejko the PR description and commit message do not explain why this change is needed. It is not really obvious from looking at the diff. Please include the motivation in the PR desc/commit message - what problem does it fix?

**Comment by piodul** [comment]
I see that you have updated the PR description to include the reason behind the change. Next time, if the PR is ready for review, please leave a comment or re-request review via the GitHub interface - editing the PR description does not trigger any notifications so I was unaware that it is ready.

**Comment by piodul** [comment]
@sylwiaszunejko Please also add some description to the commit message. The PR description is not preserved in any way in the git history.

It also looks that for some reason your username and email were put into quotes when committing. GitHub does not associate this commit with your account. Your previous commit on the `continuous_integration` branch looks fine:

```
[piodul@potwor2 seastar-rs]$ git log kfernandez31/continuous_integration 
commit 7e4a9bf186f00d44afe0783c67039b571fbe869c (kfernandez31/continuous_integration)
Author: “sylwiaszunejko” <“sylwia.szunejko@gmail.com”>
Date:   Sun Jan 15 18:50:57 2023 +0100

    Add RUSTDOCFLAGS to cargo test

commit adfe8e4b0eb3d181f771a425998c9d8865c04fb9
Author: sylwiaszunejko <sylwia.szunejko@gmail.com>
Date:   Fri Dec 30 08:50:29 2022 +0100

    Create rust.yml with format, install Seastar, build and linter steps
```

Please adjust the username and email in the commit.

**Comment by sylwiaszunejko** [comment]
I have changed commit message.

**Review by piodul — APPROVED** [review]

**Pull request merged**
